; Rice theme — paleta Gruvbox + creme, igual ao resto do rice (waybar, kitty, wlogout)
[Rice]
text               = ebdbb2
subtext            = a89984
main               = 282828
main-elevated      = 3c3836
highlight          = 3c3836
highlight-elevated = 504945
sidebar            = 282828
player             = 282828
card               = 3c3836
shadow             = 1d2021
selected-row       = 504945
button             = a89984
button-active      = f9f5d7
button-disabled    = 504945
tab-active         = f9f5d7
notification       = f9f5d7
notification-error = cc241d
misc               = 665c54
