preload = /home/matheus/Pictures/wallpapers/anime-gruvbox.png

wallpaper {
    monitor = eDP-1
    path = /home/matheus/Pictures/wallpapers/anime-gruvbox.png
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/matheus/Pictures/wallpapers/anime-gruvbox.png
}

splash = false
