background {
    monitor =
    path = /home/matheus/Pictures/wallpapers/anime-gruvbox.png
    blur_passes = 2
    blur_size = 5
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    outer_color = rgb(d65d0e)
    inner_color = rgb(282828)
    font_color = rgb(ebdbb2)
    placeholder_text = Senha...
    fade_on_empty = false
    position = 0, -50
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 90
    font_family = JetBrainsMono Nerd Font
    color = rgb(ebdbb2)
    position = 0, 150
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%A, %d de %B"
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    color = rgb(a89984)
    position = 0, 50
    halign = center
    valign = center
}
